import Head from 'next/head'
import WalletBar from '../components/WalletBar'

export default function Home() {

  return (
    <>
      <Head>
        <title>Pufu-app</title>
        <meta name="description" content="Generated by create-starknet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WalletBar />
      </main>
    </>
  )
}
